@host = http://localhost:3001
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJpbmdAam9lLmNvbSIsInN1YiI6MiwiaWF0IjoxNzM2OTkzMzQ5LCJleHAiOjE3MzcwNzk3NDl9.vudkkxveRsTepmJTgmXvLXfrn-Yp4yWpq8arckQq3j0
@userId = 2

### Login

POST {{host}}/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "bing@joe.com",
    "password": "fleem"
}

### Get users

GET {{host}}/auth/users HTTP/1.1
Authorization: Bearer {{token}}

### Signup user

POST {{host}}/auth/signup HTTP/1.1
Content-Type: application/json

{
    "email": "bing@joe.com",
    "password": "fleem"
}

### Get user by ID

GET {{host}}/auth/users/{{userId}} HTTP/1.1
Authorization: Bearer {{token}}

### Update user by ID

PUT {{host}}/auth/users/{{userId}} HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "email": "floom@jumbo.com",
    "hashedPassword": "asdf123"
}

### Delete user by ID

DELETE {{host}}/auth/users/{{userId}} HTTP/1.1
Authorization: Bearer {{token}}
