@host = http://localhost:3001
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHF1aXAuY29tIiwic3ViIjoxLCJpYXQiOjE3Mzg5ODMxMzEsImV4cCI6MTczOTA2OTUzMX0.qxomxK0mtF_RuoFzjfdvlUHzfIrUt2wJvvqwxadUiDs
@channelId = 2
@timestamp = 2025-01-30T12:00:00
@name = sports

### Get channels

GET {{host}}/channels HTTP/1.1
Authorization: Bearer {{token}}

### Get channel by name
GET {{host}}/channels/{{name}} HTTP/1.1
Authorization: Bearer {{token}}

### Get channel messages

GET {{host}}/channels/{{channelId}}/messages?timestamp={{timestamp}} HTTP/1.1
Authorization: Bearer {{token}}

### Create channel message

POST {{host}}/channels/{{channelId}}/messages
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "text": "This is a test messasge"
}
